import argparse

from attr import dataclass
from core.ytmusic_manager import YTMusicManager
from ytmusicapi import YTMusic

ytm = YTMusic()

@dataclass
class ChannelSongData:
    channel_id: str
    video_id: str
    title: str
    artists: list[str]
    album: str

def get_aritst_songs(channel_id: str) -> list[ChannelSongData]:
    """指定されたYouTubeチャンネルの曲一覧を取得する"""
    artist = ytm.get_artist(channel_id)
    browseId = artist["songs"]["browseId"]
    songs = ytm.get_playlist(playlistId=browseId,
                             limit=None)

    ret_songs:list[ChannelSongData]= []
    for song in songs["tracks"]:
        # Inst / Off Vocal を除く
        title = song["title"].lower()
        if "inst" in title or "off vocal" in title:
            print(f'Skipping instrumental/off vocal track: {song["title"]}')
            continue

        add_item = ChannelSongData(
            channel_id=channel_id,
            video_id=song["videoId"],
            title=song["title"],
            artists=[item["name"] for item in song.get("artists",["Unknown Artist"])],
            album=song.get("album",{"name":"Unknown Album"})["name"],
        )
        ret_songs.append(add_item)

    return ret_songs

def create_download_script(song_data: list[ChannelSongData], output_file: str) -> None:
    """曲IDのリストからダウンロードスクリプトを作成するダミー関数"""
    with open(output_file, "w", encoding="utf-8") as f:
        # f.write("#!/bin/bash\n")
        f.write("# PowerShell スクリプト\n")
        f.write(f"# Generated by create_dl_script_from_yt.py\n\n")
        f.write(f"# Channel ID: {song_data[0].channel_id}\n")
        f.write(f"# Total songs: {len(song_data)}\n\n")

        for song_item in song_data:
            f.write(f"# {song_item.title} - {', '.join(song_item.artists)}\n")
            f.write(f"yt-dlp --audio-only --no-overwrite https://www.youtube.com/watch?v={song_item.video_id}\n")
    
    print(f"ダウンロードスクリプトが作成されました: {output_file}")

def main():
    parser = argparse.ArgumentParser(description="YouTube ダウンロードスクリプト作成ツール")
    parser.add_argument("--url", type=str, required=True, help="YouTubeチャンネルのURL", metavar="URL")
    parser.add_argument("--output", type=str, required=False, help="出力スクリプトファイルのパス",metavar="OUTPUT_FILE")

    args = parser.parse_args()

    # https://music.youtube.com/channel/UC8p5DuhOMR7fZLgnybVX0sA
    channel_metadata = get_aritst_songs(args.url)
    # print(channel_metadata)

    if channel_metadata is None or len(channel_metadata) == 0:
        print("指定されたチャンネルから曲を取得できませんでした。")
        return

    fallback_filename = f"scripts_{channel_metadata[0].artists[0]}_{channel_metadata[0].channel_id}.ps1"
    output_file = args.output if args.output else fallback_filename

    create_download_script(channel_metadata, output_file)

if __name__ == "__main__":
    main()